### ISSUE TITLE
Code quality gate

### ISSUE THREAD

**Issue by zelytra** [sculkmp/Sculk#2]
In the `README.md` file a code quality badge is present. Without any actions run to check the code quality.

Suspecting it's fake and has no sens of it presence.

Solution 1 : Remove the badge
Solution 2 : Setup a code quality checker like Sonarcube and add a real badge for code quality check

**Comment by JblusItsMe** [comment]
Hello,

Ok, all right, I’ll delete it temporarily, and add it later, and find out about Sonarcube, thanks for your feedback 😉
